name: untitled
description: A new To Do App.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_slidable: ^1.2.0
  provider: ^6.0.5
  logger: ^1.4.0
  google_fonts: ^4.0.4
  intl: ^0.18.0
  shared_preferences: ^2.1.2
  hive_flutter: ^1.1.0
  dio: ^5.2.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
flutter_intl:
  enabled: true
